use_frameworks!

platform :ios, '9.0'

target 'YHFloatContainerView_Example' do
  pod 'YHFloatContainerView', :path => '../'
  pod 'Masonry'

  target 'YHFloatContainerView_Tests' do
    inherit! :search_paths

    
  end
end
